name: Test Composite Action

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4

      - uses: ./
        with:
          source-repo: ${{ github.repository }}
          source-ref: ${{ github.sha }}
          database-name: "Test Database"
          database-desc: "Minimal schema for testing the composite action."
          migrations-path: test/migrations
          skip-publish: false
